name: jobaventure
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `fl
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.2  # Version mise à jour
  shared_preferences: ^2.0.13
  jwt_decoder: ^2.0.1
  dio: ^5.0.2  
  flutter_secure_storage: ^5.0.2  
  flutter_spinkit: ^5.0.0  # Ajoutez cette ligne    # Ajout de la dépendance dio
  video_player: ^2.2.10
  chewie: ^1.3.0  # Vérifiez la dernière version sur pub.dev
  path_provider: ^2.0.11
  image_picker: ^0.8.6 # Mettez à jour à la dernière version stable
  permission_handler: ^11.3.1 
  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.1

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/aa.png
    - assets/images/ab.png
    - assets/images/ac.png
    - assets/images/DDD.png
    - assets/images/q.png
    - assets/images/d.png
    - assets/images/Loading_icon.gif
 
